app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/musicdb
    username: postgres
    password: derpo
    pool-size: 30
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
